export type Route = { kind: "home"; workspaceKey: string } | { kind: "note"; workspaceKey: string; path: string; compare?: string } | { kind: "folder"; workspaceKey: string; path: string; view: "list" | "table" | "board" | "calendar" | "timeline"; viewId?: string } | { kind: "search"; workspaceKey: string; query: string; folder: string; fileKind: string };
const registryKey = "maek:workspace-keys";
type Registry = Record<string, string>;
function registry(): Registry { try { return JSON.parse(localStorage.getItem(registryKey) ?? "{}"); } catch { return {}; } }
export function pathForWorkspaceKey(key: string) { return registry()[key] ?? null; }
export function workspaceKeyFor(root: string): string { const entries = registry(); const existing = Object.entries(entries).find(([, value]) => value === root)?.[0]; if (existing) return existing; const key = crypto.randomUUID().replace(/-/g, "").slice(0, 12); entries[key] = root; localStorage.setItem(registryKey, JSON.stringify(entries)); return key; }
function decodePath(value: string | undefined): string | null { if (value === undefined) return ""; try { const result = decodeURIComponent(value); return !result.startsWith("/") && !result.split("/").includes("..") ? result : null; } catch { return null; } }
export function parseRoute(location = window.location): Route | null { const match = location.pathname.match(/^\/w\/([^/]+)\/(home|note|folder|search)(?:\/(.*))?$/); if (!match) return null; const [, workspaceKey, kind, encoded] = match; const path = decodePath(encoded); if (!workspaceKey || path === null) return null; const params = new URLSearchParams(location.search); if (kind === "home") return { kind, workspaceKey }; if (kind === "note") { const compare = decodePath(params.get("compare") ?? undefined); return compare === null ? null : { kind, workspaceKey, path, compare: compare || undefined }; } if (kind === "folder") { const requested=params.get("view"); const view=requested==="table"||requested==="board"||requested==="calendar"||requested==="timeline"?requested:"list"; return { kind, workspaceKey, path, view, viewId:params.get("viewId")??undefined }; } return { kind: kind as "search", workspaceKey, query: params.get("q") ?? "", folder: params.get("folder") ?? "", fileKind: params.get("kind") ?? "" }; }
export function routeHref(route: Route): string { const root = `/w/${encodeURIComponent(route.workspaceKey)}`; if (route.kind === "home") return `${root}/home`; if (route.kind === "note") return `${root}/note/${encodeURIComponent(route.path)}${route.compare ? `?compare=${encodeURIComponent(route.compare)}` : ""}`; if (route.kind === "folder") { const query=new URLSearchParams({view:route.view});if(route.viewId)query.set("viewId",route.viewId);return `${root}/folder/${encodeURIComponent(route.path)}?${query}`; } const query = new URLSearchParams(); if (route.query) query.set("q", route.query); if (route.folder) query.set("folder", route.folder); if (route.fileKind) query.set("kind", route.fileKind); return `${root}/search?${query}`; }
export function navigate(route: Route, replace = false) { history[replace ? "replaceState" : "pushState"]({}, "", routeHref(route)); window.dispatchEvent(new PopStateEvent("popstate")); }
