export type Route = { kind: "home"; workspaceKey: string } | { kind: "note"; workspaceKey: string; path: string } | { kind: "folder"; workspaceKey: string; path: string; view: "list" | "table" | "board" | "calendar" | "timeline"; viewId?: string };
const registryKey = "maek:workspace-keys";
type Registry = Record<string, string>;
function registry(): Registry { try { return JSON.parse(localStorage.getItem(registryKey) ?? "{}"); } catch { return {}; } }
export function pathForWorkspaceKey(key: string) { return registry()[key] ?? null; }
export function workspaceKeyFor(root: string): string { const entries = registry(); const existing = Object.entries(entries).find(([, value]) => value === root)?.[0]; if (existing) return existing; const key = crypto.randomUUID().replace(/-/g, "").slice(0, 12); entries[key] = root; localStorage.setItem(registryKey, JSON.stringify(entries)); return key; }
function decodePath(value: string | undefined): string | null { if (value === undefined) return ""; try { const result = decodeURIComponent(value); return !result.startsWith("/") && !result.split("/").includes("..") ? result : null; } catch { return null; } }
export function parseRoute(location = window.location): Route | null { const match = location.pathname.match(/^\/w\/([^/]+)\/(home|note|folder)(?:\/(.*))?$/); if (!match) return null; const [, workspaceKey, kind, encoded] = match; const path = decodePath(encoded); if (!workspaceKey || path === null) return null; const params = new URLSearchParams(location.search); if (kind === "home") return { kind, workspaceKey }; if (kind === "note") return { kind, workspaceKey, path }; const requested=params.get("view"); const view=requested==="table"||requested==="board"||requested==="calendar"||requested==="timeline"?requested:"list"; return { kind: "folder", workspaceKey, path, view, viewId:params.get("viewId")??undefined }; }
export function routeHref(route: Route): string { const root = `/w/${encodeURIComponent(route.workspaceKey)}`; if (route.kind === "home") return `${root}/home`; if (route.kind === "note") return `${root}/note/${encodeURIComponent(route.path)}`; const query=new URLSearchParams({view:route.view});if(route.viewId)query.set("viewId",route.viewId);return `${root}/folder/${encodeURIComponent(route.path)}?${query}`; }
export function navigate(route: Route, replace = false) { history[replace ? "replaceState" : "pushState"]({}, "", routeHref(route)); window.dispatchEvent(new PopStateEvent("popstate")); }
