import { useEffect, useState } from "react";
import { FileCode, FileText, Search, X } from "lucide-react";
import { api } from "../../host";
import { navigate, type Route } from "../../lib/routes";
type Result = { path: string; kind: string; mtimeMs: number; count: number; matches: { text: string; start: number; end: number }[] };
export function ContentSearch({ route, onClose }: { route: Extract<Route, { kind: "search" }>; onClose?: () => void }) {
  const [query, setQuery] = useState(route.query); const [results, setResults] = useState<Result[]>([]); const [loading, setLoading] = useState(false);
  useEffect(() => setQuery(route.query), [route.query]);
  useEffect(() => { if (!route.query.trim()) { setResults([]); return; } const controller = new AbortController(); const timer = window.setTimeout(() => { setLoading(true); void api<{ results: Result[] }>(`/api/search?q=${encodeURIComponent(route.query)}&folder=${encodeURIComponent(route.folder)}&kind=${encodeURIComponent(route.fileKind)}`, "GET", undefined, undefined, controller.signal).then((value) => setResults(value.results)).catch(() => {}).finally(() => setLoading(false)); }, 250); return () => { controller.abort(); window.clearTimeout(timer); }; }, [route.query, route.folder, route.fileKind]);
  return <div className="flex-1 min-h-0 overflow-auto px-8 py-7"><div className="mx-auto max-w-3xl"><div className="flex items-center justify-between mb-5"><h1 className="text-xl font-semibold">Search workspace</h1>{onClose && <button className="icon-button" onClick={onClose} aria-label="Close search"><X size={16}/></button>}</div><form onSubmit={(event) => { event.preventDefault(); navigate({ ...route, query }); }} className="flex gap-2 mb-4"><input autoFocus aria-label="Search content" className="workspace-input flex-1" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search note and text content"/><button className="icon-button" aria-label="Run search"><Search size={16}/></button></form><div className="flex gap-2 mb-6"><input aria-label="Folder filter" className="workspace-input flex-1" value={route.folder} onChange={(event) => navigate({ ...route, folder: event.target.value }, true)} placeholder="Folder filter"/><select aria-label="File type filter" className="workspace-input" value={route.fileKind} onChange={(event) => navigate({ ...route, fileKind: event.target.value }, true)}><option value="">All text files</option><option value="markdown">Markdown</option><option value="text">Text</option><option value="html">HTML</option></select></div>{loading && <p className="text-sm text-muted-text">Searching…</p>}{!loading && route.query && results.length === 0 && <p className="text-sm text-muted-text">No matching files.</p>}<ul className="flex flex-col gap-3">{results.map((result) => <li key={result.path} className="glass-panel border border-default rounded-xl p-4"><button className="text-left w-full" onClick={() => navigate({ kind: "note", workspaceKey: route.workspaceKey, path: result.path })}><span className="flex items-center gap-2 font-medium">{/\.html$/i.test(result.path) ? <FileCode size={15}/> : <FileText size={15}/>}{result.path}</span>{result.matches.map((match, index) => <p key={index} className="text-sm text-muted-text mt-2">{match.text.slice(0, match.start)}<mark>{match.text.slice(match.start, match.end)}</mark>{match.text.slice(match.end)}</p>)}</button></li>)}</ul></div></div>;
}
